version: "3.7"
services:

  service:
    environment:
      - FLASK_ENV=development
    build: ./service
    volumes:
      - ./service:/app/service
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
